### ISSUE TITLE
Remove private @zowe repo from .npmrc

### ISSUE THREAD

**Issue by crshnburn** [zowe/zowe-cli-web-help-generator#4]
Currently this project is configured to download libraries in the @zowe repo from the private jfrog artifact repository which contributors do not have access to. The .npmrc file checked into the project should be updated to remove the configuration so that the required libraries are downloaded from the npm repository.

**Comment by t1m0thyj** [comment]
@crshnburn The JFrog Artifactory repository configured in this project's .npmrc file is a public NPM repository that all contributors should have access to without any authentication.

The same Artifactory URL is used for `@zowe:registry` by several other projects under the Zowe org, for example [zowe-cli](https://github.com/zowe/zowe-cli/blob/master/.npmrc) and [zowe-cli-cics-plugin](https://github.com/zowe/zowe-cli-cics-plugin/blob/master/.npmrc).

Perhaps there are firewall restrictions at your site, that do not permit access to this registry?
