### ISSUE TITLE
Inaccuracies in readme.md

### ISSUE THREAD

**Issue by robertblum-psi** [zowe/zowe-cli-web-help-generator#44]
The doc states:

> Copy the template file zowe.template.json to zowe.json in the root of the project. _This file is ignored by git._

> Add your copyright text to a file named .copyright in the root of the repository. _This file will be ignored by git._

The file was not automatically ignored by git. What you meant to state was: _You can add this file to .gitignore._  

![image](https://github.com/zowe/zowe-cli-web-help-generator/assets/70774083/9fd8b18f-de2e-4201-b6e9-e47a9f37922f)

**Comment by t1m0thyj** [comment]
Both the `zowe.json` and `.copyright` files are included in this repository's `.gitignore`: https://github.com/zowe/zowe-cli-web-help-generator/blob/master/.gitignore

If the steps to contribute web help are performed in the root of this project as instructed in the readme, then these files will be automatically ignored by git. If the steps are performed in a different directory, then you would need to add a `.gitignore` in that directory, which is outside the scope of the readme.
